{% set name = "nectarchain" %}
{% set version = "0.1.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/nectarchain-{{ version }}.tar.gz
  sha256: 1ee59866fc861cede16d3cc9358729a247529292634630298f7219b46456a495

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - python =3
    - setuptools >=64.0.3
    - setuptools-scm >=3.4
    - pip
  run:
    - python =3
    - astropy
    - browser-cookie3
    - ctapipe =0.19
    - ctapipe-io-nectarcam
    - mechanize
    - pandas

test:
  imports:
    - nectarchain
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/cta-observatory/nectarchain
  summary: Analysis chain for the CTA MSTN NectarCAM prototype
  license: BSD-3-Clause
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - jlenain
