{% set name = "nectarchain" %}
{% set version = "0.2.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/nectarchain-{{ version }}.tar.gz
  sha256: ec73e0ec205d406d7d45a0aaea1961b39dd563362dd7a0beca32a6e7d0621638

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=64.0.3
    - setuptools-scm >=3.4
    - pip
  run:
    - python >={{ python_min }}
    - ctapipe =0.19
    - ctapipe-io-nectarcam
    - lmfit
    - pandas
    - pyqt
    - pyqtgraph
    - scipy =1.11.4
    - zeo
    - zodb

test:
  imports:
    - nectarchain
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/cta-observatory/nectarchain
  summary: Analysis chain for the CTA MSTN NectarCAM prototype
  license: BSD-3-Clause
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - jlenain
