{% set name = "nectarchain" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/nectarchain-{{ version }}.tar.gz
  sha256: 3b4b06063303822ed133c8fefc2a7eb60f1fb1158bc9365de7d259cf762587ca

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=64.0.3
    - setuptools-scm >=3.4
    - pip
  run:
    - python >={{ python_min }}
    - ctapipe =0.19
    - ctapipe-io-nectarcam
    - pandas
    - scipy =1.11.4
    - zeo
    - zodb
    - lmfit  # needed into TRR
    - h5py  # needed into TRR (should be removed to use I/O methods of containers)
    - pyqt6
    - pyqtgraph

test:
  imports:
    - nectarchain
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/cta-observatory/nectarchain
  summary: Analysis chain for the CTA MSTN NectarCAM prototype
  license: BSD-3-Clause
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - jlenain
