{% set name = "nectarchain" %}
{% set version = "0.1.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/nectarchain-{{ version }}.tar.gz
  sha256: 777be6b6d9f752b5607505e1431dcb9117216e03f9a7ff028a62211e4c8ebfc2

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - python =3
    - setuptools >=64.0.3
    - setuptools-scm >=3.4
    - pip
  run:
    - python =3
    - ctapipe =0.19
    - ctapipe-io-nectarcam
    - pandas

test:
  imports:
    - nectarchain
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/cta-observatory/nectarchain
  summary: Analysis chain for the CTA MSTN NectarCAM prototype
  license: BSD-3-Clause
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - jlenain
