{% set name = "nectarchain" %}
{% set version = "0.1.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/nectarchain-{{ version }}.tar.gz
  sha256: e421ecf3ef51f70cd0e033cdd03d2d638afb4f3886a361cfd79e874b5a5732f0

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - python =3
    - setuptools >=64.0.3
    - setuptools-scm >=3.4
    - pip
  run:
    - python =3
    - astropy
    - ctapipe =0.12
    - ctapipe-io-nectarcam
    - numpy <1.23
    - protozfits =2.0
    - pytables >=3.7

test:
  imports:
    - nectarchain
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/cta-observatory/nectarchain
  summary: Analysis chain for the CTA MSTN NectarCAM prototype
  license: BSD-3-Clause
  license_file: licenses/LICENSE.rst

extra:
  recipe-maintainers:
    - jlenain
