{% set name = "nectarchain" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/nectarchain-{{ version }}.tar.gz
  sha256: 4d62c20deec022480fe9cc623957bd77837b6ab816ef14e72298cfaf078596ce

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=64.0.3
    - setuptools-scm >=3.4
    - pip
  run:
    - python >={{ python_min }}
    - ctapipe =0.24
    - ctapipe-io-nectarcam =0.2
    - lmfit
    - pandas
    - pyqt
    - pyqtgraph
    - scipy
    - zeo
    - zodb

test:
  imports:
    - nectarchain
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/cta-observatory/nectarchain
  summary: Analysis chain for the CTA MSTN NectarCAM prototype
  license: BSD-3-Clause
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - jlenain
